name: Deploy Heroku Review Apps

description: Deploy a Heroku Review App from GitHub
branding:
  icon: 'git-pull-request'
  color: 'purple'
inputs:
  github_token:
    required: true
    description: Github access token
  heroku_api_token:
    required: true
    description: Heroku API token
  heroku_pipeline_id:
    required: true
    description: The UUID of your herkou pipeline to create review app within

runs:
  using: node12
  main: dist/index.js
